name: Run QA Automation Tests

on:
  push:
  workflow_dispatch:
      inputs:
        tags:
          description: "Cucumber scenario tags"
          required: true
          default: "smoke"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK version
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: 'maven'

      - name: Start Selenium Grid and run tests
        run: |
          make selenium-up
          make test

      # For more details read - https://allurereport.org/docs/integrations-github/#3-set-up-publishing-github-pages
      # Assumes that the branch used for GitHub Pages is called gh-pages
      - name: Fetch Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure report action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: ${{ vars.ALLURE_RESULTS_PATH }}
          allure_history: allure-history
          keep_reports: 10

      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
